#!/usr/bin/env python3
"""consumer explain — turn consumed knowledge into an explainer video project.

Reads a distilled corpus (seeds/keywords/concepts) and emits a RENDERMILL-
compatible project (slides.py + slides/*.html per the video_claw project
schema), plus a zero-dependency storyboard.md so anyone can read/produce the
video without any render tooling.

Narration follows the house plain-language law (STE-80): short sentences,
active voice, one idea per sentence. Seeds come from real spoken prose, so
they already talk like a person.

Usage:
  python3 explain.py ./my-course/distilled --title "The Funnel Machine" --out ./explainer
  python3 explain.py ./my-course/distilled --title "..." --out ./explainer --short   # 1080x1920

If you have rendermill installed:
  cd explainer && rendermill render      # -> out/<title>.mp4
Without it: read storyboard.md — full script, on-screen text, timings.
"""
import argparse
import json
import os
import re
import sys
import time

# Explainer-video voice law (house, 2026-10-05): explainers use Voidcaller
# (Justin's EL IVC clone, eleven_v3). Override per-project if the surface
# needs a different voice — the field is the switch.
DEFAULT_VOICE = {"provider": "elevenlabs", "voice_id": "VuzA0dgWCTwUZobOSnRk",
                 "model": "eleven_v3", "speaking_rate": 1.0}

SLIDE_TEMPLATE = """<!DOCTYPE html><html><head><meta charset="utf-8"><style>
html,body{{margin:0;height:100%;background:#0e0f13;color:#e8eaf0;
font-family:-apple-system,'Segoe UI',Roboto,sans-serif;display:flex;
align-items:center;justify-content:center;position:relative}}
.kicker{{position:absolute;top:8vh;left:8vw;font-size:26px;color:#7c5cff;
letter-spacing:.22em;text-transform:uppercase}}
h1{{font-size:{size}px;margin:0;text-align:center;padding:0 8vw;line-height:1.15;max-width:84vw}}
.accent{{color:#7c5cff}}
</style></head><body>
<div class="kicker">{kicker}</div>
<h1>{headline}</h1>
</body></html>"""


def load_corpus(distilled):
    def j(name, key):
        p = os.path.join(distilled, name)
        return json.load(open(p)).get(key, []) if os.path.exists(p) else []
    return j("concepts.json", "concepts"), j("keywords.json", "keywords"), j("next-best-seeds.json", "seeds")


def ste80(sentence):
    """Plain-language pass: collapse filler, cap runaway sentences. Seeds are
    spoken prose already; this only trims obvious offenders."""
    s = re.sub(r"\b(you know|like I said|basically|kind of|sort of)\b[, ]*", "", sentence, flags=re.I)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def build_beats(concepts, keywords, seeds, max_beats=4):
    """Hook -> escalating beats -> payoff. Hook = strongest seed (the
    first-3-seconds law); beats walk the concept clusters; payoff = the
    second-strongest seed."""
    hook = ste80(seeds[0]["sentence"]) if seeds else "Here is the one idea that matters."
    payoff = ste80(seeds[1]["sentence"]) if len(seeds) > 1 else "That is the whole idea."
    beats = []
    cl = concepts[:max_beats] or [{"phrase": k["term"]} for k in keywords[:max_beats]]
    for i, c in enumerate(cl, 1):
        headline = c["phrase"].title()
        # narration: a seed that mentions the concept, else a plain claim
        line = next((ste80(s["sentence"]) for s in seeds[2:]
                     if c["phrase"].lower() in s["sentence"].lower()), None)
        if not line:
            line = f"{headline}. What it is, and how to use it."
        beats.append({"kicker": f"{i:02d}", "headline": headline, "narration": line})
    return hook, beats, payoff


def est_seconds(text):
    return max(2.0, len(text.split()) / 2.5)  # ~150 wpm


def write_project(out, title, hook, beats, payoff, orientation, voice):
    slides_dir = os.path.join(out, "slides")
    os.makedirs(slides_dir, exist_ok=True)
    slides_cfg = []

    def add(html_name, kicker, headline, narration, big=True):
        size = 92 if big else 72
        with open(os.path.join(slides_dir, html_name), "w") as f:
            f.write(SLIDE_TEMPLATE.format(kicker=kicker, headline=headline, size=size))
        slides_cfg.append({"type": "html", "html": f"slides/{html_name}",
                           "narration": narration, "speed": 1.12})

    add("hook.html", "START HERE", hook, hook)
    for b in beats:
        add(f"beat-{b['kicker']}.html", b["kicker"], b["headline"], b["narration"], big=False)
    add("payoff.html", "THE POINT", payoff, payoff)

    config = {"title": re.sub(r"[^a-z0-9-]+", "-", title.lower()).strip("-"),
              "orientation": "short" if orientation else "horizontal",
              "out_path": "out/explainer.mp4", "tts": voice}

    with open(os.path.join(out, "slides.py"), "w") as f:
        f.write('"""Explainer project generated by consumer explain.py\n'
                f'Title: {title}\nGenerated: {time.strftime("%Y-%m-%d %H:%M")}\n'
                'Render (rendermill installed): rendermill render\n'
                'No rendermill? Read storyboard.md — full script + timings.\n'
                '"""\n\nCONFIG = ' + json.dumps(config, indent=4) +
                '\n\nSLIDES = ' + json.dumps(slides_cfg, indent=4) + '\n')

    # zero-dependency storyboard
    lines = [f"# Storyboard — {title}", "",
             f"Orientation: {'1080x1920 (short)' if orientation else '1920x1080'} · "
             f"{len(slides_cfg)} slides · est {round(sum(est_seconds(s['narration']) for s in slides_cfg), 1)}s", ""]
    for i, s in enumerate(slides_cfg, 1):
        lines += [f"## Slide {i} — {os.path.basename(s['html'])}", "",
                  f"**On screen:** {re.sub(r'<[^>]+>', '', open(os.path.join(out, s['html'])).read().split('<h1>')[1].split('</h1>')[0])}",
                  f"**Narration:** {s['narration']}",
                  f"**Est:** {round(est_seconds(s['narration']), 1)}s", ""]
    with open(os.path.join(out, "storyboard.md"), "w") as f:
        f.write("\n".join(lines))
    return len(slides_cfg)


def main():
    ap = argparse.ArgumentParser(description="Distilled corpus -> explainer video project (rendermill-compatible + zero-dep storyboard)")
    ap.add_argument("distilled")
    ap.add_argument("--title", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--short", action="store_true", help="1080x1920 orientation (Shorts/Reels/TikTok)")
    ap.add_argument("--voice-id", default=DEFAULT_VOICE["voice_id"])
    ap.add_argument("--voice-model", default=DEFAULT_VOICE["model"])
    a = ap.parse_args()

    if not os.path.isdir(a.distilled):
        sys.exit(f"FATAL: {a.distilled} not found")
    concepts, keywords, seeds = load_corpus(a.distilled)
    if not (concepts or seeds):
        sys.exit(f"FATAL: no concepts or seeds in {a.distilled} — run distill.py first")

    hook, beats, payoff = build_beats(concepts, keywords, seeds)
    voice = dict(DEFAULT_VOICE, voice_id=a.voice_id, model=a.voice_model)
    n = write_project(a.out, a.title, hook, beats, payoff, a.short, voice)
    print(json.dumps({"ok": True, "out": os.path.abspath(a.out), "slides": n,
                      "rendermill": f"cd {a.out} && rendermill render",
                      "zero_dep": os.path.abspath(os.path.join(a.out, 'storyboard.md'))},
                     indent=2))


if __name__ == "__main__":
    main()